import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ModernNavbar from '@/components/ModernNavbar';
import Footer from '@/components/Footer';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
   
      >
        <ModernNavbar />

        {children}
        <Footer/>
      </body>
    </html>
  );
}
